stages:
  preprocessing:
    cmd: python adClassifier/preprocessing.py
    deps:
    - adClassifier/preprocessing.py
    - ad_labeling/completions
    - data/en-US.csv.gz
    params:
    - adClassifier/params.yaml:
      - preprocessing
    outs:
    - data/df.parquet.gzip
    - data/df_test.parquet.gzip
    - data/df_train.parquet.gzip
  main_pipeline:
    cmd: python adClassifier/main_pipeline.py
    deps:
    - adClassifier/main_pipeline.py
    - data/df_test.parquet.gzip
    - data/df_train.parquet.gzip
    params:
    - adClassifier/params.yaml:
      - main_pipeline
    outs:
    - data/df_test_labeled.parquet.gzip
    - data/df_train_labeled.parquet.gzip
    - data/models/label.model
    - data/models/randomforest.model
    - data/models/vectorizer.model
  labeller_analysis:
    cmd: jupyter nbconvert notebooks/labeller_analysis.ipynb --to html --execute
    deps:
    - data/df_test.parquet.gzip
    - data/df_test_labeled.parquet.gzip
    - data/df_train.parquet.gzip
    - data/df_train_labeled.parquet.gzip
    - notebooks/labeller_analysis.ipynb
    params:
    - adClassifier/params.yaml:
      - notebook
