preprocessing:
  data_folder: /Users/tjpajala/PycharmProjects/adClassifier/data
  seed: 42
  test_percent_size: 0.33
  completions_folder: /Users/tjpajala/PycharmProjects/adClassifier/ad_labeling/completions
labeling_functions:
  data_folder: /Users/tjpajala/PycharmProjects/adClassifier/data
  metrics_folder: metrics_data
  seed: 125
  # labeling functions need to be the same string as the variable name in labeling_functions.py
  lfs: ["lf_mentions_trump",
        "lf_mentions_maga",
        "lf_mentions_bidenharris",
        "lf_mentions_biden",
        "lf_mentions_stop_republican"
  ]
  n_epochs: 500
  log_freq: 100
  n_estimators: 100
  class_weight: balanced_subsample
notebook:
  data_folder: data
  metrics_folder: metrics_data
  scores_file: all_runs.json